queue_rules:
  - name: default
    conditions:
      - status-success=main

pull_request_rules:
  - name: Automatically merge into master after build and review
    conditions:
      - base=master
      - status-success=main
      - 'label=ready to merge'
      - "#approved-reviews-by>=1"
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge on into release after build and approval
    conditions:
      - base~=^release-
      - status-success=main
      - "#approved-reviews-by>=1"
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge backport into release branches
    conditions:
      - head~=mergify/bp
      - author~=mergify
      - base~=^release-
      - status-success=main
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: automatic merge on changes to gradle.properties
    conditions:
      - "status-success=main"
      - files=gradle.properties
      - "#files=1"
    actions:
      queue:
        method: squash
        name: default
  - name: Automatically mergify-yaml changes to master
    conditions:
      - base=master
      - title~=^fix(mergify)
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically armory-common bump changes to master
    conditions:
      - title~=^fix\(spinnakerBump\)
      - author=armory-jenkins
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
