apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinghy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinghy
  template:
    metadata:
      labels:
        app: dinghy
    spec:
      containers:
      - name: dinghy
        image: armory-docker-all.jfrog.io/armory/dinghy:${parameters['tag']}
        command: ["/opt/armory/bin/dinghy"]
        args: ["-mode", "multi-tenant"]
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 2
        volumeMounts:
          - name: dinghy
            mountPath: /opt/spinnaker/config
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: dinghy
          configMap:
            name: dinghy