apiVersion: v1
kind: Service
metadata:
  name: dinghy
  labels:
    app: dinghy
spec:
  # TODO in the future if we setup external-dns we can have our own DNS
  # TODO annotations here.
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: dinghy
