apiVersion: v1
kind: ConfigMap
metadata:
  name: dinghy
data:
  dinghy.yml: |
    yeti:
      url: <update-me>
    metrics:
      newRelic:
        applicationName: Cloud Dinghy - Prod
    sql:
      enabled: true
      baseUrl: <update-me>
      databaseName: dinghy
      user: dinghy
      password: <update-me>
      eventlogsOnly: false