apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dinghy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dinghy
    spec:
      containers:
      - name: dinghy
        image: gcr.io/cloud-armory/dinghy
        resources:
          requests:
            memory: "128M"
            cpu: "1000m"
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 2